services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: binaryuser
      POSTGRES_PASSWORD: binarypass
      POSTGRES_DB: binarybets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U binaryuser -d binarybets"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: https://github.com/wingnut144/BinaryBets.git#main:backend
      args:
        GITHUB_REPO: https://github.com/wingnut144/BinaryBets.git
        GITHUB_BRANCH: main
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://binaryuser:binarypass@postgres:5432/binarybets
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: https://github.com/wingnut144/BinaryBets.git#main:frontend
      args:
        GITHUB_REPO: https://github.com/wingnut144/BinaryBets.git
        GITHUB_BRANCH: main
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

  db-init:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: binarypass
    volumes:
      - ./init-from-github.sh:/init-from-github.sh
    entrypoint: ["/bin/bash", "/init-from-github.sh"]

volumes:
  postgres_data:
