x-github: &gh "wingnut144"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: binaryuser
      POSTGRES_PASSWORD: binarypass
      POSTGRES_DB: binarybets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U binaryuser -d binarybets"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git &&
             git clone --depth 1 https://github.com/*gh/binary-bets.git /tmp/repo &&
             cp -r /tmp/repo/backend/* /app/ &&
             npm install &&
             npm start"
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://binaryuser:binarypass@postgres:5432/binarybets
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git &&
             git clone --depth 1 https://github.com/*gh/binary-bets.git /tmp/repo &&
             cp -r /tmp/repo/frontend/* /app/ &&
             npm install &&
             npm run build &&
             npx serve -s dist -l 3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db-init:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: binarypass
    command: >
      sh -c "apk add --no-cache curl bash &&
             curl -sSL https://raw.githubusercontent.com/*gh/binary-bets/main/init.sql |
             psql -h postgres -U binaryuser -d binarybets"

volumes:
  postgres_data:
