services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: binaryuser
      POSTGRES_PASSWORD: binarypass
      POSTGRES_DB: binarybets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U binaryuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://binaryuser:binarypass@postgres:5432/binarybets
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres_data:
