name: Build and Push All Services

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  trigger-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Build
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'backend.yml',
              ref: 'main'
            })
  
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Build
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'frontend.yml',
              ref: 'main'
            })
